export const FETCH_SERIALS_IN_PROGRESS = 'FETCH_SERIALS_IN_PROGRESS';
export const FETCH_SERIALS_SUCCESS = 'FETCH_SERIALS_SUCCESS';
export const FETCH_SERIALS_FAILED  = 'FETCH_SERIALS_FAILED';

export const SELECT_SERIAL = 'SELECT_SERIAL';