export const FETCH_SERIAL_LIST_IN_PROGRESS = 'FETCH_SERIAL_LIST_IN_PROGRESS';
export const FETCH_SERIAL_LIST_SUCCESS = 'FETCH_SERIAL_LIST_SUCCESS';
export const FETCH_SERIAL_LIST_FAILED = 'FETCH_SERIAL_LIST_FAILED';

export const FETCH_SERIAL_LIST = 'FETCH_SERIAL_LIST';

export const SERIAL_SELECTED = 'SERIAL_SELECTED';